### ISSUE TITLE
Покупка MystCase

### ISSUE THREAD

**Issue by hardwareSpaceman** [EvilSquad01/ArcMine#6]
1) Лобби.
2) При покупке MystCase выдаются не сами кейсы, а их подарочные версии (т.е. их можно подарить игроку, но самим открыть нельзя).
3) Купить кейсы в магазине главного меню.
4) Скриншот ниже.
5) realDosed

![image](https://user-images.githubusercontent.com/38529177/82303980-5f50ec00-99c4-11ea-8b92-ab821e6924d0.png)

**Comment by EvilSquad01** [comment]
Данные кейсы и сделаны для того, чтобы дарить.
Обычные кейсы вы можете создать в алтаре.
Название раздела с кейсами во внутриигровом магазине изменено.
